name: pop-tools-dev
channels:
  - conda-forge
dependencies:
  - bottleneck
  - codecov
  - toolz
  - docrep
  - numba
  - pip
  - pooch
  - pytest-cov
  - pyyaml
  - scipy
  - pip:
      - git+https://github.com/pydata/xarray.git#egg=xarray
      - git+https://github.com/dask/dask.git#egg=dask
      - git+https://github.com/xgcm/xgcm.git#egg=xgcm
