name: pop-tools-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - bottleneck
  - codecov
  - docrep=0.2.7
  - netcdf4
  - numba>=0.52
  - pip
  - pooch>=1.3.0
  - pytest-cov
  - pyyaml>=5.3.1
  - scipy
  - toolz
  - pip:
      - git+https://github.com/pydata/xarray.git#egg=xarray
      - git+https://github.com/dask/dask.git#egg=dask
      - git+https://github.com/xgcm/xgcm.git#egg=xgcm
