name: pop-tools-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - bottleneck
  - codecov
  - dask>=2.14
  - docrep==0.2.7
  - nbsphinx
  - netcdf4
  - numba>=0.52
  - pip
  - pooch>=1.3.0
  - pytest-cov
  - pyyaml>=5.3.1
  - scipy
  - xarray>=0.16.1
  - xgcm
  - watermark
